jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
      - image: postgres:17  # Or your desired PostgreSQL version
        environment:
          POSTGRES_USER: topicos1  # Set your desired user
          POSTGRES_PASSWORD: 123456  # Set your desired password
          POSTGRES_DB: ecommerce  # Set your desired database name
        ports:
          - "5432:5432"
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
              sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          name: Run Tests with PostgreSQL Configuration
          command: mvn verify -Dquarkus.datasource.jdbc.url="jdbc:postgresql://localhost:5432/ecommerce" \
                             -Dquarkus.datasource.username="topicos1" \
                             -Dquarkus.datasource.password="123456"
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository