@startuml ecommerce
class Pessoa{
  - nome : String
  - email : String
  - cpf : String
  - telefone : String
  - aniversario : LocalDate
}

class Cadastro{
  - responsavel : String
  - categoria : String
  - status : Status 
  - dataCadastro : LocalDateTime

}

Enum Status{
  ATIVO : int
  INATIVO : int
  PENDENTE : int
}

Cadastro "1" -- "1" Status
Cadastro <-- Funcionario
Cadastro --> Produto

class Funcionario{
  - idFuncionario : Long
  - cargo : String 
  - salario : String
}

Funcionario "1" --> "1" Pessoa

Enum Sexo{
  FEMININO : int
  MASCULINO : int
}

Funcionario "*"--"1" Sexo

class Fornecedor{
  - idFornecedor : Long
  - nome : String
  - endereco : String 
  - email : String
  - telefone : String
  - cnpj : String
}

class Produto{
  - idProduto : Long
  - nomeProduto : String
  - preco : Double
  - material : String
  - altura : Integer
  - largura: Integer
  - peso : Integer
}

class Camera{
  - idCameras : Long
  - sensor : List<sensor>
  - processador : List<processador>
  - resolucao : String
  - lente : List<lente>
  - formatoAudio : FormatoAudio
  - formatoImagem : FormatoImagem
  - iso : String
  - obturador : Obturador
  - peso : Double
}

Enum FormatoVideo{
MP4 : String
AVI : String
MOV : String
WMV : String
MKV : String
FLV : String
}

Enum FormatoAudio{
MP3 : String
WAV : String
FLAC : String
AAC : String
OGG : String
}

Enum FormatoImagem{
JPEG : String
PNG : String
TIFF : String
RAW : String
DNG : String
}

Enum Obturador{
OBTURADOR_ELETRONICO : String
OBTURADOR_MECANICO : String
OBTURADOR_ELETRONICO_MECANICO : String
}

Camera "1" -- "*" Obturador
Camera "1" -- "*" FormatoImagem
Camera "1" -- "*" FormatoAudio
Camera "1" -- "*" FormatoVideo

class Lente{
  - tipoMontagem : TipoMontagem
  - distanciaFocal : DistanciaFocal
  - abertura : Abertura
  - tipoLente : TipoLente
  - compatibilidade : Compatibilidade
  - dimensoes : String
  - peso : Double
}

Enum DistanciaFocal{
  WIDE_ANGLE : String
  ULTRA_WIDE_ANGLE : String
  STANDARD : String
  TELEPHOTO : String
  SUPER_TELEPHOTO : String
  FISHEYE : String
  MACRO : String
}

Enum Abertura{
  F1_4 : String
  F2 : String
  F2_8 : String
  F4 : String
  F5_6 : String
  F8 : String
  F11 : String
  F16 : String
  F22 : String
}

Enum TipoLente{
  PRIME : String
  ZOOM : String
  TILT_SHIFT : String
  PERSPECTIVE_CONTROL : String
  ANAMORPHIC : String
}

Lente "*" <-- "*" Camera
Abertura "*" --"1" Lente
Lente "1" -- "1" TipoLente
DistanciaFocal "1..*"-- "1" Lente

Fornecedor "1" --> "n" Produto
Produto <|-- Camera
Produto <|-- Lente
@enduml