@startuml ecommerce
class Pessoa{
  - nome : String
  - email : String
  - cpf : String
  - aniversario : LocalDate
  - sexo : Sexo
  - listaTelefone : List<Telefone>
}

Pessoa "1" *--> "*" Telefone

class Cadastro{
  - idCadastro : Long
  - responsavel : String
  - categoria : String
  - status : Status 
}

DefaultEntity <|-- Cadastro

Enum Status{
  ATIVO
  INATIVO
  PENDENTE
}

Cadastro --> Status
Cadastro "*" --> "1" Funcionario
Cadastro "1" --> "1" Produto

class Funcionario{
  - idFuncionario : Long
  - cargo : String 
}

class Cliente{
  - idCliente
}

Pessoa "1" <-- "1" Funcionario
Pessoa "1" <-- "1" Cliente

Enum Sexo{
  FEMININO
  MASCULINO
}

Pessoa --> Sexo

class Fornecedor{
  - idFornecedor : Long
  - nome : String
  - endereco : String 
  - email : String
  - cnpj : String
  - listaTelefone : List<Telefone>
}

Fornecedor "1" *--> "*" Telefone

class Produto{
  - idProduto : Long
  - nomeProduto : String
  - preco : Double
  - material : String
  - dimensoes : String
  - nomeModelo : String
}

class Camera{
  - idCameras : Long
  - conectividade : String
  - resolucao : String
  - telaArticulavel : Boolean
  - telaSensivelToque : Boolean
  - tela : String
  - iso : String
  - flashPopUp : Boolean
  - garantia : Integer
}

class Marca{
  - idMarca : Long
  - nome : String
}

Marca "1" <--* "*" Produto

class Lente{
  - idLente : String
  - compatibilidade : String
  - distanciaFocal : Integer
  - diametroFiltro : Integer
  - montagem : String
}

class DefaultEntity{
  - id : Long
  - dataCadastro : LocalDateTime
  - dataAlteracao : LocalDateTime
}

class Telefone{
  - codigoArea : String
  - numero : String
}

DefaultEntity <|-- Pessoa

Fornecedor "1" --> "*" Produto
Produto <|-- Camera
Produto <|-- Lente
@enduml